let arrSong = [
  {
    id: 1,
    name: "id 072019 - W/n",
    singer: "W/n",
    audio: "/assets/audio/Id072019-WN.mp3",
    image: "/assets/img/Id072019-WN.jpg",
  },
  {
    id: 2,
    name: "À Lôi",
    singer: "Double2T, Masew",
    audio: "/assets/audio/ALoi-Double2TMasew.mp3",
    image: "/assets/img/ALoi-Double2TMasew.jpg",
  },
  {
    id: 3,
    name: "Mong Một Ngày Anh Nhớ Đến Em",
    singer: "Huỳnh James, Pjnboys",
    audio: "/assets/audio/MongMotNgayAnhNhoDenEm.mp3",
    image: "/assets/img/MongMotNgayAnhNhoDenEm.jpg",
  },
  {
    id: 4,
    name: "Waiting For You",
    singer: "MONO, Onionn",
    audio: "/assets/audio/WaitingForYou.mp3",
    image: "/assets/img/WaitingForYou.jpg",
  },
  {
    id: 5,
    name: "Hãy Trao Cho Anh",
    singer: "Sơn Tùng MTP",
    audio: "/assets/audio/HayTraoChoAnh.mp3",
    image: "/assets/img/HayTraoChoAnh.jpg",
  },
  {
    id: 6,
    name: "Bên Trên Tầng Lầu",
    singer: "Tăng Duy Tân",
    audio: "/assets/audio/BenTrenTangLau.mp3",
    image: "/assets/img/BenTrenTangLau.jpg",
  },
  {
    id: 7,
    name: "Ánh Sao Và Bầu Trời",
    singer: "T.R.I",
    audio: "/assets/audio/AnhSaoVaBauTroi.mp3",
    image: "/assets/img/AnhSaoVaBauTroi.jpg",
  },
  {
    id: 8,
    name: "Yêu 5",
    singer: "Rhymastic",
    audio: "/assets/audio/Yeu5.mp3",
    image: "/assets/img/Yeu5.jpg",
  },
  {
    id: 9,
    name: "Chân Ái",
    singer: "Orange, Khói, Châu Đăng Khoa",
    audio: "/assets/audio/ChanAi.mp3",
    image: "/assets/img/ChanAi.jpg",
  },
  {
    id: 10,
    name: "Nàng Thơ",
    singer: "Hoàng Dũng",
    audio: "/assets/audio/NangTho.mp3",
    image: "/assets/img/NangTho.jpg",
  },
];
